# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021-2022, Intel Corporation
#
---
k8s_definitions_dir: "/opt/tmdb"
client_results_dir: "/opt/redis-cluster-benchmark-results"

#

chart_version: "4.2.4"
clusters_count_default: 1
collect_emon_data_default: False

logdir_default: "/home/logs"
log_dir_structure: "redis_cluster_logs"

multiple_clusters_balanced_default: True
namespace_prefix: "redis-cluster"
redis_nodes_count: 6

target_fw_ver_default: "01.02.00.5444"
test_mode: "{{ lookup('env', 'test_mode') }}"
warm_up_benchmark_run_default: False

#

# Redis & TieredMemDB specific
dram_pmem_ratio_default: "1 3"
multithreading_default: True
pmem_variant_default: "multiple"
threads_default: 8

# memtier_benchmark specific
clients_default: 3
datasize_default: 1024
pipeline_default: 1
requests_default: 150000000
run_count_default: 3
test_time_default: 1800
ratio_default: "1:4"
key_pattern_default: "G:G"

# Registry specific - Redis
redis_registry_default: "docker.io"
redis_repository_default: "bitnami/redis-cluster"
redis_tag_default: "6.0.9-debian-10-r59"

# Registry specific - TieredMemDB
tmdb_registry_default: ""
tmdb_repository_default: ""
tmdb_tag_default: ""

#

clients: "{{ lookup('env', 'clients') | default(clients_default, true) }}"
clusters_count: "{{ lookup('env', 'clusters_count') | default(clusters_count_default, true) }}"
collect_emon_data: "{{ lookup('env', 'collect_emon_data') | default(collect_emon_data_default, true) }}"
datasize: "{{ lookup('env', 'datasize') | default(datasize_default, true) }}"
dram_pmem_ratio: "{{ lookup('env', 'dram_pmem_ratio') | default(dram_pmem_ratio_default, true) }}"
key_pattern: "{{ lookup('env', 'key_pattern') | default(key_pattern_default, true) }}"
logdir: "{{ lookup('env', 'logdir') | default(logdir_default, true) }}"
multiple_clusters_balanced: "{{ lookup('env', 'multiple_clusters_balanced') | default(multiple_clusters_balanced_default, true) }}"
multithreading: "{{ lookup('env', 'multithreading') | default(multithreading_default, true) }}"
pipeline: "{{ lookup('env', 'pipeline') | default(pipeline_default, true) }}"
pmem_variant: "{{ lookup('env', 'pmem_variant') | default(pmem_variant_default, true) }}"
ratio: "{{ lookup('env', 'ratio') | default(ratio_default, true) }}"
redis_registry: "{{ lookup('env', 'redis_registry') | default(redis_registry_default, true) }}"
redis_repository: "{{ lookup('env', 'redis_repository') | default(redis_repository_default, true) }}"
redis_tag: "{{ lookup('env', 'redis_tag') | default(redis_tag_default, true) }}"
requests: "{{ lookup('env', 'requests') | default(requests_default, true) }}"
run_count: "{{ lookup('env', 'run_count') | default(run_count_default, true) }}"
target_fw_ver: "{{ lookup('env', 'target_fw_ver') | default(target_fw_ver_default, true) }}"
test_time: "{{ lookup('env', 'test_time') | default(test_time_default, true) }}"
threads: "{{ lookup('env', 'threads') | default(threads_default, true) }}"
tmdb_registry: "{{ lookup('env', 'tmdb_registry') | default(tmdb_registry_default, true) }}"
tmdb_repository: "{{ lookup('env', 'tmdb_repository') | default(tmdb_repository_default, true) }}"
tmdb_tag: "{{ lookup('env', 'tmdb_tag') | default(tmdb_tag_default, true) }}"
warm_up_benchmark_run: "{{ lookup('env', 'warm_up_benchmark_run') | default(warm_up_benchmark_run_default, true) }}"

python_packages:
  - "boto3"
  - "kubernetes"
  - "openpyxl"
  - "openshift"
  - "openpyxl"
  - "boto3"

# vi:et:sw=2 ts=2 sts=2 ft=ansible
