name: k8s-redis-cluster
on:  [push, pull_request]

jobs:
  linux:
    name: k8s-redis-cluster
    runs-on: ubuntu-latest
    env:
      HOST_WORKDIR:   ${{ github.workspace }}
      LICENSE_TAG:    BSD-3-Clause
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install file -y

      - name: Check license headers
        run: $HOST_WORKDIR/utils/check_license/check-headers.sh $HOST_WORKDIR $LICENSE_TAG

      - name: Find ansible files to lint
        id: vars
        run: echo ::set-output name=ansible_files::$(grep -lr 'ft=ansible' ansible-playbook)

      - name: Run ansible linter
        uses: ansible/ansible-lint-action@master
        with:
          args: "-p -c .ansible-lint"
          targets: ${{ steps.vars.outputs.ansible_files }}
          override-deps: |
            ansible-lint==4.3.7
